apiVersion: v1
kind: Pod
metadata:
 name: adhocpod24
 labels:
  adhoc: kajalq2
spec:
 containers:
 - image: nginx
   name: testpod
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k2
  name: q2svkajal
spec:
 ports:
 - name: myport
   port: 80
   protocol: TCP
   targetPort: 80
 selector:
  x: hello
  type:Nodeport

