apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: adhockajalq41
 labels:
    x: hello
spec:
  selector:
    matchLabels:
      adhoc: kajalq4
  replicas: 5
  template:
    metadata:
     name: rs11
     labels:
      adhoc: kajalq4
    spec:
      containers:
      - name: rcpod11
        image: 6367400/may2020q1:v1
        ports:
	- containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: Pod
  name: q4svckajal1
spec:
  ports:
    - name: myport
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    adhoc: kajal4
  type: LoadBalancer